import operator
from typing import Annotated, Any, Dict, List, Optional
from pydantic import BaseModel, Field
from typing_extensions import TypedDict


class DecisionMemo(BaseModel):
    """A decision memo generated by an agent."""
    perspective: str = Field(description="The perspective or focus of this memo (e.g., cost, risk, speed)")
    assumptions: List[str] = Field(description="Key assumptions made")
    strategy: str = Field(description="The recommended strategy")
    risks: List[str] = Field(description="Potential risks of this strategy")
    second_order_effects: List[str] = Field(description="Anticipated second-order effects")


class AgentConfig(BaseModel):
    """Configuration for spawning a child agent."""
    perspective: str
    instructions: str


class GraphState(TypedDict):
    """The state of the overall orchestrator graph."""
    task_description: str
    
    # The configurations for agents to spawn
    agent_configs: List[AgentConfig]
    
    # Use Annotated with operator.add to append generated memos to the list
    # As each parallel nested agent runs, it will append its output here.
    memos: Annotated[List[DecisionMemo], operator.add]
    
    # The final ranked strategies from the evaluator
    ranked_strategies: List[Dict[str, Any]]
    
    
class AgentState(TypedDict):
    """The state passed down to individual parallel agents."""
    task_description: str
    perspective: str
    instructions: str
